In [25]:
import pandas as pd 
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

# Load the File

In [26]:
df=pd.read_csv(r"D:\Udemy CrashCourses\Udemy\Data Analyst Bootcamp\ML-PROJECT\notebook\data\stud.csv")

In [27]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [40]:
df.dtypes

gender                           str
race_ethnicity                   str
parental_level_of_education      str
lunch                            str
test_preparation_course          str
math_score                     int64
reading_score                  int64
writing_score                  int64
dtype: object

In [34]:
X = df.drop(columns=['math_score'])  # Independent features

In [35]:
X.shape

(1000, 7)

In [36]:
y=df["math_score"]

In [38]:
y.shape

(1000,)

# Create a columns to tranform with three columns

In [41]:
cat_cols = ['gender', 'race_ethnicity', 'parental_level_of_education', 
            'lunch', 'test_preparation_course']

X[cat_cols] = X[cat_cols].astype('object')

In [42]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

print("Numerical:", num_features.tolist())
print("Categorical:", cat_features.tolist())

Numerical: ['reading_score', 'writing_score']
Categorical: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [44]:
num_features = X.select_dtypes(include=['int64','float64']).columns
cat_features = X.select_dtypes(include=['object','str']).columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numerical_transform = StandardScaler()
oh_transform = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transform, cat_features),    # ✅ comma
        ("StandardScaler", numerical_transform, num_features)  # ✅ num_features
    ]
)

print(preprocessor)

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(),
                                 Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='str')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['reading_score', 'writing_score'], dtype='str'))])

# Shape of dataset

In [45]:
X=preprocessor.fit_transform(X)

In [48]:
X.shape

(1000, 19)

# Train and Test Split

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

X_train.shape,X_test.shape

((800, 19), (200, 19))

# Evaluation Our Model

In [60]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error

In [65]:
from sklearn.metrics import (
    mean_absolute_error, 
    mean_squared_error, 
    r2_score,
    root_mean_squared_error  # ← naya function import karo
)

def evaluate_model(true, predict):
    mae  = mean_absolute_error(true, predict)
    rmse = root_mean_squared_error(true, predict)  # ← seedha ye use karo
    r2   = r2_score(true, predict)
    return mae, rmse, r2

In [66]:
def evaluate_model(true, predict):
    mae  = mean_absolute_error(true, predict)
    rmse = np.sqrt(mean_squared_error(true, predict))  # ← sqrt se RMSE nikalo
    r2   = r2_score(true, predict)
    return mae, rmse, r2

In [67]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [69]:
## Beginning Model Training
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
   
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 5.3231
- Mean Absolute Error: 4.2667
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3940
- Mean Absolute Error: 4.2148
- R2 Score: 0.8804
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.5938
- Mean Absolute Error: 5.2063
- R2 Score: 0.8071
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5197
- Mean Absolute Error: 5.1579
- R2 Score: 0.8253
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 5.3233
- Mean Absolute Error: 4.2650
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3904
- Mean Absolute Error: 4.2111
- R2 Score: 0.8806
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 5.7091
- Mean Absolute Error: 4.5175
- R2 Score: 0.8554
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.2583
- Mean Absolute Error: 5.6370
- R2 Score: 0.7835
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.2795
- Mean Absolute Error: 0.0187
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.8743
- Mean Absolute Error: 6.1850
- R2 Score: 0.7452
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 2.2869
- Mean Absolute Error: 1.8185
- R2 Score: 0.9768
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0040
- Mean Absolute Error: 4.6157
- R2 Score: 0.8519
===================================

# Train Model

In [70]:
models = {
    "Linear Regression":      LinearRegression(),
    "Lasso":                  Lasso(),
    "Ridge":                  Ridge(),
    "K-Neighbors Regressor":  KNeighborsRegressor(),
    "Decision Tree":          DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
}

# ============================================
# STEP 10 — TRAIN aur EVALUATE KARO
# ============================================
model_list = []
r2_list    = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred  = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae,  model_test_rmse,  model_test_r2  = evaluate_model(y_test,  y_test_pred)

    model_list.append(list(models.keys())[i])
    r2_list.append(model_test_r2)

    print(list(models.keys())[i])
    print('Model performance for Training set')
    print("- RMSE:     {:.4f}".format(model_train_rmse))
    print("- MAE:      {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))
    print('----------------------------------')
    print('Model performance for Test set')
    print("- RMSE:     {:.4f}".format(model_test_rmse))
    print("- MAE:      {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    print('='*35)
    print('\n')

# ============================================
# STEP 11 — RESULTS DATAFRAME
# ============================================
report = pd.DataFrame(
    list(zip(model_list, r2_list)),
    columns=['Model Name', 'R2 Score']
).sort_values(by='R2 Score', ascending=False)

print("\n--- Model Comparison ---")
print(report)

# ============================================
# STEP 12 — BEST MODEL
# ============================================
best_model_name = report.iloc[0]['Model Name']
best_r2_score   = report.iloc[0]['R2 Score']

print("\nBest Model:  ", best_model_name)
print("Best R2 Score: {:.4f}".format(best_r2_score))

Linear Regression
Model performance for Training set
- RMSE:     5.3231
- MAE:      4.2667
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- RMSE:     5.3940
- MAE:      4.2148
- R2 Score: 0.8804
===================================


Lasso
Model performance for Training set
- RMSE:     6.5938
- MAE:      5.2063
- R2 Score: 0.8071
----------------------------------
Model performance for Test set
- RMSE:     6.5197
- MAE:      5.1579
- R2 Score: 0.8253
===================================


Ridge
Model performance for Training set
- RMSE:     5.3233
- MAE:      4.2650
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- RMSE:     5.3904
- MAE:      4.2111
- R2 Score: 0.8806
===================================


K-Neighbors Regressor
Model performance for Training set
- RMSE:     5.7091
- MAE:      4.5175
- R2 Score: 0.8554
----------------------------------
Model performance for Test set
- RMSE:     7.2583
- MAE:      5.6370
- R2 Score: 0.7835
===================================


Decision Tree
Model performance for Training set
- RMSE:     0.2795
- MAE:      0.0187
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- RMSE:     7.9250
- MAE:      6.2350
- R2 Score: 0.7419
===================================


Random Forest Regressor
Model performance for Training set
- RMSE:     2.3279
- MAE:      1.8389
- R2 Score: 0.9760
----------------------------------
Model performance for Test set
- RMSE:     5.9942
- MAE:      4.6387
- R2 Score: 0.8523
===================================



--- Model Comparison ---
                Model Name  R2 Score
2                    Ridge  0.880593
0        Linear Regression  0.880433
5  Random Forest Regressor  0.852346
1                    Lasso  0.825320
3    K-Neighbors Regressor  0.783497
4            Decision Tree  0.741903

Best Model:   Ridge
Best R2 Score: 0.8806

In [71]:
pd.DataFrame(list(zip(model_list,r2_list)),columns=["Mode Name","R2_Score"]).sort_values(by=["R2_Score"],ascending=False)

                 Mode Name  R2_Score
2                    Ridge  0.880593
0        Linear Regression  0.880433
5  Random Forest Regressor  0.852346
1                    Lasso  0.825320
3    K-Neighbors Regressor  0.783497
4            Decision Tree  0.741903

In [74]:
# Loop khatam hone ke baad — last model ki predictions use hongi
pred_df = pd.DataFrame({
    "Actual Value":    y_test,
    "Predicted Value": y_test_pred,
    "Difference":      y_test - y_test_pred
})

print(pred_df.head(10))

     Actual Value  Predicted Value  Difference
521            91            76.33       14.67
737            53            52.89        0.11
740            80            76.26        3.74
660            74            76.87       -2.87
411            84            79.65        4.35
678            81            85.48       -4.48
626            69            65.55        3.45
513            54            55.19       -1.19
859            87            75.08       11.92
136            51            52.30       -1.30

In [73]:
pred_df

     Actual Value  Predicted value  Difference
521            91            76.33       14.67
737            53            52.89        0.11
740            80            76.26        3.74
660            74            76.87       -2.87
411            84            79.65        4.35
..            ...              ...         ...
408            52            46.58        5.42
332            62            61.82        0.18
208            74            67.99        6.01
613            65            67.65       -2.65
78             61            67.99       -6.99

[200 rows x 3 columns]

In [ ]:
df.describe()

In [ ]:
df.duplicated().sum()

In [ ]:
df.info()

# check unique value

In [ ]:
df.nunique()

# Exploring Data

In [ ]:
print("Category in 'gender' variable:   ",  end=" ")
print(df['gender'].unique)
print("Category in 'race_ethnicity' variable:   ",  end=" ")
print(df['race_ethnicity'].unique)
print("Category in 'Parent_level_of education' variable:   ",  end=" ")
print(df['parental_level_of_education'].unique)
print("Category in 'lunch' variable:   ",  end=" ")
print(df['lunch'].unique)
print("Category in 'test_preparation_course' variable:   ",  end=" ")
print(df['test_preparation_course'].unique)
print("Category in 'gender' variable:   ",  end=" ")
print(df['gender'].unique)

# define categorical and numerical features

In [ ]:
numeric_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'str']).columns.tolist()

print("We have {} numerical features: {}".format(len(numeric_features), numeric_features))
print("\nWe have {} categorical features: {}".format(len(categorical_features), categorical_features))

# Adding column for total score

In [ ]:
df["total score"]=df["math_score"]+df["reading_score"]+df["writing_score"]
df["average"]=df["total score"]/3
df.head()

In [ ]:
reading_math_full=df[df["reading_score"]==100]["average"].count()
writing_score=df[df["writing_score"]==100]["average"].count()
math_score=df[df["math_score"]==100]["average"].count()

In [ ]:
print(f"Number of the Student with full mark in Math:{math_score}")
print(f"Number of the Student with full mark in writing:{writing_score}")
print(f"Number of the Student with full mark in reading:{reading_math_full}")

In [ ]:
reading_math_full=df[df["reading_score"]<=20]["average"].count()
writing_score=df[df["writing_score"]<=20]["average"].count()
math_score=df[df["math_score"]<=20]["average"].count()

print(f"Number of the Student with full mark in Math:{math_score}")
print(f"Number of the Student with full mark in writing:{writing_score}")
print(f"Number of the Student with full mark in reading:{reading_math_full}")

# Exploring Data (Matplotlib)

In [ ]:
fig, axs = plt.subplots(1, 2, figsize=(15,7))  # subplots ✅

plt.subplot(121)
sns.histplot(data=df, x="average", bins=30, kde=True, color='g')
plt.title("Overall Average Score")  # Title bhi add karo

plt.subplot(122)
sns.histplot(data=df, x="average", hue="gender", kde=True)
# color='g' mat do jab hue use ho — hue apna color deta hai
plt.title("Average Score by Gender")

plt.show()